apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lasample
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: linuxacademycontent/gitops:hellov1.1
